### ISSUE TITLE
Connect error

### ISSUE THREAD

**Issue by FastAccountForPull** [ataranlen/civcraft#103]
[16:02:43 INFO]: [CivCraft] ========= Initializing SQL =========
[16:02:43 INFO]: [CivCraft]      Using yobo_local as database.
[16:02:43 INFO]: [CivCraft]      Building Connection Pool for GAME database.
[16:02:43 ERROR]: Error occurred while enabling CivCraft v2.1-REBORN (Is it up to date?)
java.lang.NoClassDefFoundError: com/jolbox/bonecp/BoneCPConfig
        at com.avrgaming.civcraft.database.ConnectionPool.<init>(ConnectionPool.java:36) ~[?:?]
        at com.avrgaming.civcraft.database.SQL.initialize(SQL.java:97) ~[?:?]
        at com.avrgaming.civcraft.main.CivCraft.onEnable(CivCraft.java:248) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[Civka.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340) [Civka.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [Civka.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357) [Civka.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317) [Civka.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414) [Civka.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378) [Civka.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333) [Civka.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263) [Civka.jar:git-Spigot-db6de12-18fbb24]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525) [Civka.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_111]
Caused by: java.lang.ClassNotFoundException: com.jolbox.bonecp.BoneCPConfig
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_111]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[Civka.jar:git-Spigot-db6de12-18fbb24]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[Civka.jar:git-Spigot-db6de12-18fbb24]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
        ... 14 more
[16:02:43 INFO]: [dynmap-civcraft] Enabling dynmap-civcraft v1.0
[16:02:43 INFO]: CIVCRAFT DYNMAP ENABLING
[16:02:43 INFO]: Using update peroid:12000
[16:02:43 INFO]: Server permissions file permissions.yml is empty, ignoring it
[16:02:43 INFO]: Done (6,879s)! For help, type "help" or "?"
[16:02:43 INFO]: [dynmap] Loading default resource pack
[16:02:45 INFO]: CIVCRAFT-DYNMAP: Running update!
[16:02:45 INFO]: CIVCRAFT-DYNMAP: Update finished.
[16:02:46 WARN]: [AutoSaveWorld] Plugin ChatEx attempted to establish connection https://api.curseforge.com/servermods/files?projectIds=65863 in main server thread
[16:02:46 WARN]: [AutoSaveWorld] Plugin ChatEx attempted to establish connection socket://api.curseforge.com:443 in main server thread
[16:02:46 INFO]: [ChatEx] There is no new version available. You are up-to-date!

**Comment by YourCoal** [comment]
Are you sure your SQL databases are turned on?

**Comment by BenjaminGoGurts** [comment]
Add META-INF in your civcraft build

**Comment by ataranlen** [comment]
![screenshot 2017-03-26 21 01 31](https://cloud.githubusercontent.com/assets/1933566/24337989/6e95841a-1267-11e7-9c64-ea918234a031.png)

Simple, use the manifest.
