### ISSUE TITLE
SQLINIT ERROR

### ISSUE THREAD

**Issue by Domaman202** [ataranlen/civcraft#194]
![image](https://user-images.githubusercontent.com/51743763/131144044-17dd070c-2165-4bbd-8295-8689ac0eb602.png)
```log
[21:32:43 INFO]: [CivCraft] ========= Initializing SQL =========
[21:32:43 INFO]: [CivCraft]      Using game as database.
[21:32:43 INFO]: [CivCraft]      Building Connection Pool for GAME database.
[21:32:43 WARN]: java.sql.SQLException: Unable to open a test connection to the given database. JDBC url = jdbc:mysql://localhost:3306/game, username = user. Terminating connection pool (set lazyInit to true if you expect to start your database after your app). Original Exception: ------
java.sql.SQLException: Access denied for user 'user'@'localhost' (using password: YES)
        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
        at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
        at java.sql.DriverManager.getConnection(DriverManager.java:664)
        at java.sql.DriverManager.getConnection(DriverManager.java:247)
        at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
        at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
        at com.avrgaming.civcraft.database.ConnectionPool.<init>(ConnectionPool.java:46)
        at com.avrgaming.civcraft.database.SQL.initialize(SQL.java:115)
        at com.avrgaming.civcraft.main.CivCraft.onEnable(CivCraft.java:261)
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
        at java.lang.Thread.run(Thread.java:748)
------

[21:32:43 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:32:43 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:32:43 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:32:43 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[21:32:43 WARN]:        at com.jolbox.bonecp.PoolUtil.generateSQLException(PoolUtil.java:192)
[21:32:43 WARN]:        at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:422)
[21:32:43 WARN]:        at com.avrgaming.civcraft.database.ConnectionPool.<init>(ConnectionPool.java:46)
[21:32:43 WARN]:        at com.avrgaming.civcraft.database.SQL.initialize(SQL.java:115)
[21:32:43 WARN]:        at com.avrgaming.civcraft.main.CivCraft.onEnable(CivCraft.java:261)
[21:32:43 WARN]:        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
[21:32:43 WARN]:        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[21:32:43 WARN]:        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[21:32:43 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
[21:32:43 WARN]:        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
[21:32:43 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
[21:32:43 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
[21:32:43 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
[21:32:43 WARN]:        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
[21:32:43 WARN]:        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
[21:32:43 WARN]:        at java.lang.Thread.run(Thread.java:748)
[21:32:43 WARN]: Caused by: java.sql.SQLException: Access denied for user 'user'@'localhost' (using password: YES)
[21:32:43 WARN]:        at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
[21:32:43 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[21:32:43 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[21:32:43 WARN]:        at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:931)
[21:32:43 WARN]:        at com.mysql.jdbc.MysqlIO.secureAuth411(MysqlIO.java:4031)
[21:32:43 WARN]:        at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1296)
[21:32:43 WARN]:        at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2338)
[21:32:43 WARN]:        at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2371)
[21:32:43 WARN]:        at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2163)
[21:32:43 WARN]:        at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:794)
[21:32:43 WARN]:        at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
[21:32:43 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[21:32:43 WARN]:        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[21:32:43 WARN]:        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[21:32:43 WARN]:        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[21:32:43 WARN]:        at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[21:32:43 WARN]:        at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:378)
[21:32:43 WARN]:        at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:305)
[21:32:43 WARN]:        at java.sql.DriverManager.getConnection(DriverManager.java:664)
[21:32:43 WARN]:        at java.sql.DriverManager.getConnection(DriverManager.java:247)
[21:32:43 WARN]:        at com.jolbox.bonecp.BoneCP.obtainRawInternalConnection(BoneCP.java:363)
[21:32:43 WARN]:        at com.jolbox.bonecp.BoneCP.<init>(BoneCP.java:416)
[21:32:43 WARN]:        ... 14 more
```

**Comment by BenjaminGoGurts** [comment]
You probably don't have MySQL setup correctly, you need to create 2 mysql scheme's for Civ.

**Comment by Domaman202** [comment]
Can you give more details?

**Comment by Domaman202** [comment]
Those. do i need to create 2 sql databases?
or 2 sql tables in one database?

**Comment by Domaman202** [comment]
give me you sql pls
