### ISSUE TITLE
Founding a Civ or town with a name that already exists throws an unreadable exception in game.

### ISSUE THREAD

**Issue by ataranlen** [ataranlen/civcraft#46]
Just need to handle this error condition and send a reasonable message back to the user.

```
[06:36:53] [Server thread/WARN]: com.mysql.jdbc.exceptions.jdbc4.MySQLIntegrityConstraintViolationException: Duplicate entry 'Mirendar' for key 'name'
[06:36:53] [Server thread/WARN]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[06:36:53] [Server thread/WARN]:    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[06:36:53] [Server thread/WARN]:    at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[06:36:53] [Server thread/WARN]:    at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[06:36:53] [Server thread/WARN]:    at com.mysql.jdbc.Util.handleNewInstance(Util.java:407)
[06:36:53] [Server thread/WARN]:    at com.mysql.jdbc.Util.getInstance(Util.java:382)
[06:36:53] [Server thread/WARN]:    at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1039)
[06:36:53] [Server thread/WARN]:    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
[06:36:53] [Server thread/WARN]:    at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
[06:36:53] [Server thread/WARN]:    at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
[06:36:53] [Server thread/WARN]:    at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
[06:36:53] [Server thread/WARN]:    at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2626)
[06:36:53] [Server thread/WARN]:    at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:2111)
[06:36:53] [Server thread/WARN]:    at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1362)
[06:36:53] [Server thread/WARN]:    at com.jolbox.bonecp.PreparedStatementHandle.execute(PreparedStatementHandle.java:140)
[06:36:53] [Server thread/WARN]:    at com.avrgaming.civcraft.database.SQL.insertNow(SQL.java:510)
[06:36:53] [Server thread/WARN]:    at com.avrgaming.civcraft.database.SQL.updateNamedObject(SQL.java:388)
[06:36:53] [Server thread/WARN]:    at com.avrgaming.civcraft.object.Town.saveNow(Town.java:345)
[06:36:53] [Server thread/WARN]:    at com.avrgaming.civcraft.object.Town.newTown(Town.java:939)
[06:36:53] [Server thread/WARN]:    at com.avrgaming.civcraft.object.Civilization.newCiv(Civilization.java:588)
[06:36:53] [Server thread/WARN]:    at com.avrgaming.civcraft.threading.tasks.FoundCivSync.run(FoundCivSync.java:49)
[06:36:53] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[06:36:53] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[06:36:53] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[06:36:53] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[06:36:53] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[06:36:53] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[06:36:53] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
[06:36:53] [Server thread/WARN]: com.avrgaming.civcraft.exception.CivException: Internal Database Exception, Contact an Admin
[06:36:53] [Server thread/WARN]:    at com.avrgaming.civcraft.object.Town.newTown(Town.java:1019)
[06:36:53] [Server thread/WARN]:    at com.avrgaming.civcraft.object.Civilization.newCiv(Civilization.java:588)
[06:36:53] [Server thread/WARN]:    at com.avrgaming.civcraft.threading.tasks.FoundCivSync.run(FoundCivSync.java:49)
[06:36:53] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:71)
[06:36:53] [Server thread/WARN]:    at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:350)
[06:36:53] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.B(MinecraftServer.java:723)
[06:36:53] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.DedicatedServer.B(DedicatedServer.java:374)
[06:36:53] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.A(MinecraftServer.java:654)
[06:36:53] [Server thread/WARN]:    at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:557)
[06:36:53] [Server thread/WARN]:    at java.lang.Thread.run(Thread.java:745)
```

**Comment by ataranlen** [comment]
http://www.minetexas.com/minecraft-server-forum/showthread.php?tid=700

**Comment by ghost** [comment]
Hey,when im trying add new structure or tech or wonder i have that problem: https://gyazo.com/31dee75a9ead018fff144433eb8a89c5
And when im creating civ data error,dbg buildspawn work.
Help please =)

**Comment by ataranlen** [comment]
@TheLegion1337 that looks like a different error. Looks like a YAML issue. Open a new ticket and attach your yml files.

**Comment by ataranlen** [comment]
Some additional information: Disconnecting when in the process of founding a town or civ will break the process.

**Comment by TheLegionCrazy** [comment]
Maybe?
```
try {
create sth...
} catch (MySQLIntegrityConstraintViolationException e) {
    if (e.getMessage().contains("Duplicate entry")) 
        throw new CivException("name that already exists");
}
```

**Comment by ataranlen** [comment]
I think the root cause is deeper than just using the same name, as we already have checks in place for duplicate names.
		
```
Civilization existCiv = CivGlobal.getCiv(name);
if (existCiv != null) {
	throw new CivException(CivSettings.localize.localizedString("var_civ_found_civExists",name));
}
		
Town existTown = CivGlobal.getTown(capitolName);
if (existTown != null) {
	throw new CivException(CivSettings.localize.localizedString("var_civ_found_townExists",capitolName));
}
```

**Comment by TheLegionCrazy** [comment]
we must check defeated civs too #188
