### ISSUE TITLE
Mine Inventory not ticking

### ISSUE THREAD

**Issue by ataranlen** [ataranlen/civcraft#54]
```
[12:00:05] [Craft Scheduler Thread - 168/WARN]: org.apache.commons.lang.UnhandledException: Plugin CivCraft v1.8.0 generated an exception while executing task 56551
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Asynchronous entity track!
    at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
    at net.minecraft.server.v1_10_R1.EntityTracker.addEntity(EntityTracker.java:104)
    at net.minecraft.server.v1_10_R1.EntityTracker.track(EntityTracker.java:80)
    at net.minecraft.server.v1_10_R1.WorldManager.a(WorldManager.java:19)
    at net.minecraft.server.v1_10_R1.World.b(World.java:1028)
    at net.minecraft.server.v1_10_R1.WorldServer.b(WorldServer.java:1122)
    at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:1087)
    at net.minecraft.server.v1_10_R1.Chunk.addEntities(Chunk.java:753)
    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:136)
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:119)
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115)
    at net.minecraft.server.v1_10_R1.World.getChunkAt(World.java:329)
    at net.minecraft.server.v1_10_R1.World.getChunkAtWorldCoords(World.java:325)
    at net.minecraft.server.v1_10_R1.World.getType(World.java:753)
    at net.minecraft.server.v1_10_R1.World.updateAdjacentComparators(World.java:3064)
    at net.minecraft.server.v1_10_R1.TileEntity.update(TileEntity.java:120)
    at net.minecraft.server.v1_10_R1.TileEntityChest.setItem(TileEntityChest.java:93)
    at org.bukkit.craftbukkit.v1_10_R1.inventory.CraftInventory.setItem(CraftInventory.java:88)
    at org.bukkit.craftbukkit.v1_10_R1.inventory.CraftInventory.setContents(CraftInventory.java:82)
    at com.avrgaming.civcraft.util.MultiInventory.removeItemFromInventory(MultiInventory.java:110)
    at com.avrgaming.civcraft.util.MultiInventory.removeItem(MultiInventory.java:199)
    at com.avrgaming.civcraft.util.MultiInventory.removeItem(MultiInventory.java:221)
    at com.avrgaming.civcraft.components.ConsumeLevelComponent.consumeFromInventory(ConsumeLevelComponent.java:372)
    at com.avrgaming.civcraft.components.ConsumeLevelComponent.processConsumption(ConsumeLevelComponent.java:390)
    at com.avrgaming.civcraft.structure.Mine.consume(Mine.java:104)
    at com.avrgaming.civcraft.structure.Mine.process_mine(Mine.java:110)
    at com.avrgaming.civcraft.threading.timers.EffectEventTimer.processTick(EffectEventTimer.java:93)
    at com.avrgaming.civcraft.threading.timers.EffectEventTimer.run(EffectEventTimer.java:183)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more

```

**Comment by ataranlen** [comment]
Should be resolved now.

**Comment by ataranlen** [comment]
Seems to occur for Trade Ships now, too.

```
[14:00:09] [Craft Scheduler Thread - 16850/WARN]: org.apache.commons.lang.UnhandledException: Plugin CivCraft v1.8.0 generated an exception while executing task 7386866
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:56)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalStateException: Asynchronous entity track!
    at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
    at net.minecraft.server.v1_10_R1.EntityTracker.addEntity(EntityTracker.java:104)
    at net.minecraft.server.v1_10_R1.EntityTracker.track(EntityTracker.java:64)
    at net.minecraft.server.v1_10_R1.WorldManager.a(WorldManager.java:19)
    at net.minecraft.server.v1_10_R1.World.b(World.java:1028)
    at net.minecraft.server.v1_10_R1.WorldServer.b(WorldServer.java:1122)
    at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:1087)
    at net.minecraft.server.v1_10_R1.Chunk.addEntities(Chunk.java:753)
    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
    at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
    at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:136)
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:119)
    at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115)
    at net.minecraft.server.v1_10_R1.World.getChunkAt(World.java:329)
    at net.minecraft.server.v1_10_R1.World.getChunkAtWorldCoords(World.java:325)
    at net.minecraft.server.v1_10_R1.World.getType(World.java:753)
    at net.minecraft.server.v1_10_R1.World.updateAdjacentComparators(World.java:3064)
    at net.minecraft.server.v1_10_R1.TileEntity.update(TileEntity.java:120)
    at net.minecraft.server.v1_10_R1.TileEntityChest.setItem(TileEntityChest.java:93)
    at org.bukkit.craftbukkit.v1_10_R1.inventory.CraftInventory.setItem(CraftInventory.java:88)
    at org.bukkit.craftbukkit.v1_10_R1.inventory.CraftInventory.setContents(CraftInventory.java:82)
    at com.avrgaming.civcraft.util.MultiInventory.removeItemFromInventory(MultiInventory.java:110)
    at com.avrgaming.civcraft.util.MultiInventory.removeItem(MultiInventory.java:199)
    at com.avrgaming.civcraft.util.MultiInventory.removeItem(MultiInventory.java:213)
    at com.avrgaming.civcraft.components.TradeLevelComponent.consumeFromInventory(TradeLevelComponent.java:441)
    at com.avrgaming.civcraft.components.TradeLevelComponent.processConsumption(TradeLevelComponent.java:474)
    at com.avrgaming.civcraft.structure.TradeShip.consume(TradeShip.java:277)
    at com.avrgaming.civcraft.structure.TradeShip.process_trade_ship(TradeShip.java:283)
    at com.avrgaming.civcraft.threading.timers.EffectEventTimer.processTick(EffectEventTimer.java:113)
    at com.avrgaming.civcraft.threading.timers.EffectEventTimer.run(EffectEventTimer.java:183)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
    at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
    ... 3 more
```

**Comment by ataranlen** [comment]
Confirmed, no longer cancelling the tick. Still need to actually fix the bug.

**Comment by ataranlen** [comment]
Upping the priority on this, as it causes the server to crash pretty often.

**Comment by ataranlen** [comment]
```
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: java.lang.IllegalStateException: Asynchronous entity track!
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at org.spigotmc.AsyncCatcher.catchOp(AsyncCatcher.java:14)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.EntityTracker.addEntity(EntityTracker.java:104)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.EntityTracker.track(EntityTracker.java:66)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.WorldManager.a(WorldManager.java:19)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.World.b(World.java:1028)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.WorldServer.b(WorldServer.java:1122)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.WorldServer.a(WorldServer.java:1087)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.Chunk.addEntities(Chunk.java:753)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:45)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOProvider.callStage2(ChunkIOProvider.java:1)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.skipQueue(AsynchronousExecutor.java:337)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.util.AsynchronousExecutor.getSkipQueue(AsynchronousExecutor.java:295)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:16)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:136)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:119)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.ChunkProviderServer.getChunkAt(ChunkProviderServer.java:115)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.World.getChunkAt(World.java:329)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.World.getChunkAtWorldCoords(World.java:325)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.World.getType(World.java:753)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.World.updateAdjacentComparators(World.java:3064)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.TileEntity.update(TileEntity.java:120)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at net.minecraft.server.v1_10_R1.TileEntityChest.setItem(TileEntityChest.java:93)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.inventory.CraftInventory.setItem(CraftInventory.java:88)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.inventory.CraftInventory.setContents(CraftInventory.java:82)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at com.avrgaming.civcraft.util.MultiInventory.removeItemFromInventory(MultiInventory.java:110)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at com.avrgaming.civcraft.util.MultiInventory.removeItem(MultiInventory.java:199)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at com.avrgaming.civcraft.util.MultiInventory.removeItem(MultiInventory.java:221)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at com.avrgaming.civcraft.components.ConsumeLevelComponent.consumeFromInventory(ConsumeLevelComponent.java:372)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at com.avrgaming.civcraft.components.ConsumeLevelComponent.processConsumption(ConsumeLevelComponent.java:390)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at com.avrgaming.civcraft.structure.Mine.consume(Mine.java:106)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at com.avrgaming.civcraft.structure.Mine.process_mine(Mine.java:118)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at com.avrgaming.civcraft.threading.timers.EffectEventTimer.processTick(EffectEventTimer.java:93)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at com.avrgaming.civcraft.threading.timers.EffectEventTimer.run(EffectEventTimer.java:183)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftTask.run(CraftTask.java:71)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at org.bukkit.craftbukkit.v1_10_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
[19:00:40] [Craft Scheduler Thread - 42064/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[19:00:40] [Craft Scheduler Thread - 42064/INFO]: [CivCraft] [Town:NightFall] §cA level 1 mine's production stagnated. §a(9/24)
[19:00:40] [Server thread/ERROR]: Encountered an unexpected exception
net.minecraft.server.v1_10_R1.ReportedException: Exception ticking world
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:794) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_91]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_91]
	at net.minecraft.server.v1_10_R1.World.a(World.java:2561) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.SpawnerCreature.a(SpawnerCreature.java:122) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:227) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:783) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	... 4 more
[19:00:40] [Server thread/ERROR]: 	Cause of unexpected exception was
java.util.ConcurrentModificationException
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901) ~[?:1.8.0_91]
	at java.util.ArrayList$Itr.next(ArrayList.java:851) ~[?:1.8.0_91]
	at net.minecraft.server.v1_10_R1.World.a(World.java:2561) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.SpawnerCreature.a(SpawnerCreature.java:122) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.WorldServer.doTick(WorldServer.java:227) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:783) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:400) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:668) ~[spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:567) [spigot.jar:git-Spigot-1e4dd71-5e5cf84]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_91]
[19:00:40] [Server thread/ERROR]: This crash report has been saved to: /media/mctx/b68590ca-9d94-43d6-85d8-78ee489181c9/rivendell/./crash-reports/crash-2016-11-20_19.00.40-server.txt
```
